version: '3.8'

services:
  api:
    build: .
    container_name: imersao_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    environment:
      - PYTHONUNBUFFERED=1
    
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge